{% set version = "1.0.0.post2" %}

package:
  name: cenpy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cenpy/cenpy-{{ version }}.tar.gz
  sha256: 0a89f3cd1aba4578c54f9dd2dc83c9d45e6769d67155aa309aa8ca0698abfc19

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - pandas
    - requests
    - libpysal

test:
  imports:
    - cenpy

about:
  home: https://github.com/ljwolf/cenpy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "Explore and download data from Census APIs"

extra:
  recipe-maintainers:
    - ocefpaf
    - ljwolf
